spring:
  datasource:
    driverClassName: org.h2.Driver
    password: 12345
    url: jdbc:h2:mem:testdb
    username: sa
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  #       enabled: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
cloudinary:
  cloud-name: elenak
  api-key: 593765165896911
  api-secret: "${CLOUDINARY_SECRET}"
